steps:
  # Deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - "run"
      - "--filename=Deployment.yaml"
      - "--location=europe-west2"
      - "--cluster=autopilot-cluster-1"
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
