steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/product-app:$SHORT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/product-app:$SHORT_SHA'
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=Deployment.yaml'
      - '--location=europe-west2'
      - '--cluster=autopilot-cluster-1'
substitutions:
  _IMAGE: "gcr.io/$PROJECT_ID/product-app:$SHORT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
