steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/arcane-pillar-414807/product-app:$SHORT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ' gcr.io/arcane-pillar-414807/product-app:$SHORT_SHA'
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - '--filename=Deployment.yaml'
      - '--location=europe-west2'
      - '--cluster=autopilot-cluster-1'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
